# Generated by Django 3.1.4 on 2020-12-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='user',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер'),
        ),
    ]
