# Generated by Django 3.1.4 on 2020-12-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_promocode'),
        ('customuser', '0002_auto_20201215_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promocode', verbose_name='Промо код'),
        ),
        migrations.AddField(
            model_name='user',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promocode', verbose_name='Промо код'),
        ),
    ]
