# Generated by Django 3.1.4 on 2020-12-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcolor',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemheight',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemsize',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='buys',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_lower',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
