# Generated by Django 3.1.4 on 2020-12-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201214_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Базовый товар', 'verbose_name_plural': 'Базовые товары'},
        ),
        migrations.AddField(
            model_name='itemtype',
            name='is_show_at_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
