# Generated by Django 3.1.4 on 2020-12-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_itemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
        migrations.AddField(
            model_name='item',
            name='discount_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='item',
            name='short',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул'),
        ),
    ]
