# Generated by Django 3.1.4 on 2020-12-15 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201215_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itematstore',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.store', verbose_name='На складе'),
        ),
    ]
