# Generated by Django 3.1.4 on 2020-12-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201215_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True, verbose_name='ПромоКод')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка % по коду')),
                ('summ', models.IntegerField(default=0, verbose_name='Скидка в рублях по коду')),
            ],
            options={
                'verbose_name': 'Промо код',
                'verbose_name_plural': 'Промо коды',
            },
        ),
    ]
