# Generated by Django 3.1.4 on 2020-12-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='old_price',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Цена без скидки'),
        ),
    ]
