# Generated by Django 3.1.4 on 2020-12-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_item_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.itemcolor', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.itemtype', verbose_name='К товару'),
        ),
    ]
