# Generated by Django 3.1.4 on 2020-12-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201228_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='color',
        ),
        migrations.AlterField(
            model_name='item',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.item', verbose_name='К товару'),
        ),
    ]
