# Generated by Django 3.1.4 on 2020-12-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201228_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_show_at_home',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной'),
        ),
    ]
