# Generated by Django 3.1.4 on 2020-12-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='promo_code',
        ),
    ]
