# Generated by Django 3.1.4 on 2020-12-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_promocode'),
        ('order', '0002_auto_20201215_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promocode', verbose_name='Использованный промо-код'),
        ),
    ]
