# Generated by Django 3.1.4 on 2020-12-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price_with_code',
        ),
    ]
